name: Latest Packages

on:
  schedule:
    - cron: "0 0 * * 0" # sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.14.0
        cache: 'npm'
    - run: npm ci
    - run: npm run ng -- update >> output.txt
    - run: cat output.txt
    - run: grep "everything seems to be in order" output.txt 
